# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b09ac65922df9bd56f70d291286043e807a68e4aa65a83cf4702d478f39217feb2836bee6ef9172b701252f10de278fe8d5ef5252632f518854ddbb0e4231c27

test:
  secret_key_base: 9b5702f6aad7ad432bab2c48de3c77da7d83eb58296488a558c2c4d3df55a83e3cae6733958aa7252916e2389fe1d5e2b11fc7a798ef9f580b5ef9748586f8b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
